### ISSUE TITLE
JS integration in multi language sites is tricky

### ISSUE THREAD

**Issue by cluk33** [workshopbutler/js-widgets#30]
We have been using widgets 1.7.x for quite some time now. With newer versions the widget.js does no longer include the translation into other languages. Instead of having all translation in one file a single version of widgets.js for every language is build. While this reduces file size significantly it creates a new problem for us:
We have about 15 pages in squarespace where we want to use the german version and another 15 which should use the englisch version. Up till now we added the js include in the central configuration in squarespace and have choosen the correct language in the widget's config. With the new approach we will have to move the js include to the 2*15 pages to select the right language.
So upgrading to the next widget version will require us to edit 30 pages manually including high risk of forgetting to edit some.
So to keep the advantage of small file sizes but also enalble central management of all the wsb includes would it be possible to split the trainslation from the widget code completely? So one could include the widget code:

`<script src="https://cdn.workshopbutler.com/widgets.1.X.js" defer></script>`

and add language files as required?

```
<script src="https://cdn.workshopbutler.com/i18n-EN.1.X.js" defer></script>
<script src="https://cdn.workshopbutler.com/i18n-DE.1.X.js" defer></script>
```
That would enable users to keep the includes in one single place, which makes upgrading easy.
And one could choose the desired widget language as widget config again.

What do you think?

**Comment by overlogic** [comment]
Hi Christoph. Since version 1.18.0 we made one solid pack with all locales, you don't need separate files anymore.
